<footer>
    <div class="block small">
        <p>
            We process your IP address and cookies to analyze traffic and help us to improve your user
            experience. Please read our <a href="/Privacy">Privacy Policy</a> to learn more.
        </p>
    </div>

    <div class="block">
        <p>
            <a href="/Imprint">imprint</a>
            | <a href="/Privacy">privacy</a>
            | &copy; <a href="https://cundd.net/">cundd</a>
            2018
        </p>
    </div>
</footer>